import type { DataValue, SanityFlag } from "../../models/Dataset.ts";
import { analyzeTableStructure } from "../TableStructure.ts";
interface PdfItem { str: string; transform?: number[]; width?: number; height?: number; }
interface RowItem { text: string; x: number; width: number; }
const PDFJS_VERSION = "6.3.289";
async function loadPdfJs(): Promise<any> { const module = await import("pdfjs-dist/build/pdf.mjs"); module.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.worker.min.mjs`; return module; }
function groupLines(items: PdfItem[], tolerance: number): RowItem[][] { const sorted = items.filter((item) => item.str?.trim()).map((item) => ({ text: item.str.trim(), x: item.transform?.[4] ?? 0, y: item.transform?.[5] ?? 0, width: item.width ?? 0 })).sort((a, b) => b.y - a.y || a.x - b.x); const lines: Array<{ y: number; items: RowItem[] }> = []; for (const item of sorted) { const current = lines.find((line) => Math.abs(line.y - item.y) <= tolerance); if (current) current.items.push(item); else lines.push({ y: item.y, items: [{ text: item.text, x: item.x, width: item.width }] }); } return lines.map((line) => line.items.sort((a, b) => a.x - b.x)); }
function clusterXs(lines: RowItem[][], tolerance: number): number[] { const xs = lines.flatMap((line) => line.map((item) => item.x)).sort((a, b) => a - b); const clusters: number[] = []; for (const x of xs) { const existing = clusters.findIndex((value) => Math.abs(value - x) <= tolerance); if (existing >= 0) clusters[existing] = (clusters[existing] + x) / 2; else clusters.push(x); } return clusters; }
function makeMatrix(lines: RowItem[][], xs: number[], tolerance: number): DataValue[][] { return lines.map((line) => { const row: DataValue[] = Array(xs.length).fill(null); for (const item of line) { let best = -1; let bestDistance = Infinity; xs.forEach((x, index) => { const distance = Math.abs(x - item.x); if (distance < bestDistance) { bestDistance = distance; best = index; } }); if (best >= 0 && bestDistance <= tolerance * 2) row[best] = row[best] === null ? item.text : `${String(row[best])} ${item.text}`; } return row; }); }
export function reconstructPdfTable(lines: Array<Array<{ text: string; x: number; width?: number; y?: number }>>, tolerance: number): { rows: DataValue[][]; flags: SanityFlag[] } { const normalizedLines: RowItem[][] = lines.map((line) => line.map((item) => ({ text: item.text, x: item.x, width: item.width ?? 0 }))); const flags: SanityFlag[] = []; const usableLines = normalizedLines.filter((line) => line.length >= 2); if (usableLines.length < 3) return { rows: [], flags: [{ kind: "no-table", message: "Selectable PDF text did not contain enough aligned multi-column rows to reconstruct a table without guessing.", severity: "error" }] }; const xs = clusterXs(usableLines, tolerance); const frequent = xs.filter((x) => usableLines.filter((line) => line.some((item) => Math.abs(item.x - x) <= tolerance)).length >= Math.max(3, Math.ceil(usableLines.length * 0.4))); if (frequent.length < 2) return { rows: [], flags: [{ kind: "no-table", message: "Selectable PDF text did not show stable repeated column positions. The table was not inferred.", severity: "error" }] }; const rows = makeMatrix(usableLines, frequent, tolerance); rows.forEach((row, rowIndex) => { const nonBlank = row.filter((cell) => cell !== null).length; if (nonBlank === 0) flags.push({ kind: "merged-or-split-cell", rowIndex, message: `PDF reconstructed row ${rowIndex + 1} is empty after column alignment.`, severity: "warning" }); }); return { rows, flags }; }
export async function parsePdf(bytes: ArrayBuffer, maxPages = 200, columnTolerance = 10): Promise<{ tables: Array<{ name: string; rawRows: DataValue[][]; headers: string[]; types: ReturnType<typeof analyzeTableStructure>["types"]; flags: SanityFlag[] }>; textChars: number; pageCount: number }> { const pdfjs = await loadPdfJs(); let pdf: any; try { pdf = await pdfjs.getDocument({ data: bytes }).promise; } catch (error) { throw new Error(`PDF parsing failed: ${error instanceof Error ? error.message : String(error)}`); } if (pdf.numPages > maxPages) throw new Error(`This PDF has ${pdf.numPages} pages, above the ${maxPages}-page limit. Download fewer pages or export the table separately.`); const pageGroups: Array<{ page: number; lines: RowItem[][]; charCount: number }> = []; let totalChars = 0; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber += 1) { const page = await pdf.getPage(pageNumber); const content = await page.getTextContent(); const items = content.items as PdfItem[]; const charCount = items.reduce((sum, item) => sum + (item.str?.length ?? 0), 0); totalChars += charCount; pageGroups.push({ page: pageNumber, lines: groupLines(items, 3), charCount }); } const tables = []; for (const group of pageGroups) { const reconstructed = reconstructPdfTable(group.lines, columnTolerance); if (reconstructed.rows.length === 0) continue; const structure = analyzeTableStructure(reconstructed.rows); tables.push({ name: `PDF page ${group.page} table`, rawRows: reconstructed.rows, headers: structure.headers, types: structure.types, flags: [...structure.flags, ...reconstructed.flags] }); } return { tables, textChars: totalChars, pageCount: pdf.numPages }; }
export async function renderPdfPageToBlob(bytes: ArrayBuffer, pageNumber: number, maxPixels = 5_000_000): Promise<Blob> { const pdfjs = await loadPdfJs(); const pdf = await pdfjs.getDocument({ data: bytes.slice(0) }).promise; const page = await pdf.getPage(pageNumber); const baseViewport = page.getViewport({ scale: 1.5 }); const scale = Math.min(1, Math.sqrt(maxPixels / Math.max(baseViewport.width * baseViewport.height, 1))); const viewport = page.getViewport({ scale: 1.5 * scale }); if (typeof OffscreenCanvas === "undefined") throw new Error("This browser does not support OffscreenCanvas required for scanned-PDF OCR."); const canvas = new OffscreenCanvas(Math.ceil(viewport.width), Math.ceil(viewport.height)); const context = canvas.getContext("2d"); if (!context) throw new Error("Could not create a PDF OCR canvas."); await page.render({ canvasContext: context, viewport }).promise; return canvas.convertToBlob({ type: "image/png" }); }
