import type { SupportedFormat } from "../models/Dataset.ts";

const ZIP_SIGNATURE = [0x50, 0x4b, 0x03, 0x04];
const CFB_SIGNATURE = [0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1];
const PDF_SIGNATURE = [0x25, 0x50, 0x44, 0x46, 0x2d];
const OLE_SIGNATURE = CFB_SIGNATURE;
function startsWith(bytes: Uint8Array, signature: number[]): boolean { return signature.every((value, index) => bytes[index] === value); }
export function extensionToFormat(fileName: string): SupportedFormat { const ext = fileName.toLowerCase().split(".").pop() ?? ""; switch (ext) { case "csv": return "csv"; case "tsv": return "tsv"; case "xlsx": return "xlsx"; case "xls": return "xls"; case "ods": return "ods"; case "json": return "json-records"; case "docx": return "docx"; case "pdf": return "pdf-text"; case "md": case "markdown": return "markdown-table"; case "txt": return "text-table"; case "png": case "jpg": case "jpeg": return "image-ocr"; default: return "unknown"; } }
function decodeUtf8(bytes: Uint8Array): string { return new TextDecoder("utf-8", { fatal: false }).decode(bytes).replace(/^\ufeff/, ""); }
function looksLikeJson(text: string): boolean { const trimmed = text.trim(); if (!trimmed.startsWith("[")) return false; try { const parsed: unknown = JSON.parse(trimmed); return Array.isArray(parsed) && parsed.every((item) => item !== null && typeof item === "object" && !Array.isArray(item)); } catch { return false; } }
function delimiterScore(line: string, delimiter: string): number { let inQuotes = false; let count = 0; for (let i = 0; i < line.length; i += 1) { const ch = line[i]; if (ch === '"') { if (inQuotes && line[i + 1] === '"') { i += 1; continue; } inQuotes = !inQuotes; } else if (ch === delimiter && !inQuotes) count += 1; } return count; }
function stableDelimitedTable(lines: string[], delimiter: string): boolean { if (lines.length < 3) return false; const counts = lines.map((line) => delimiterScore(line, delimiter)); const positive = counts.filter((count) => count > 0); if (positive.length < 3) return false; const frequencies = new Map<number, number>(); for (const count of positive) frequencies.set(count, (frequencies.get(count) ?? 0) + 1); const mode = [...frequencies.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? 0; return mode > 0 && (frequencies.get(mode) ?? 0) >= Math.ceil(lines.length * 0.75); }
function looksLikeMarkdownTable(text: string): boolean { const lines = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); for (let i = 0; i + 1 < lines.length; i += 1) if (lines[i].includes("|") && /^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(lines[i + 1])) return true; return false; }
export async function detectFormat(fileName: string, bytes: ArrayBuffer): Promise<{ extensionFormat: SupportedFormat; contentFormat: SupportedFormat; evidence: string[]; hardBinarySignature: boolean }> {
  const extensionFormat = extensionToFormat(fileName); const u8 = new Uint8Array(bytes); const evidence: string[] = [];
  if (startsWith(u8, PDF_SIGNATURE)) return { extensionFormat, contentFormat: "pdf-text", evidence: ["PDF signature %PDF- detected."], hardBinarySignature: true };
  if (startsWith(u8, ZIP_SIGNATURE)) { try { const { default: JSZip } = await import("jszip"); const zip = await JSZip.loadAsync(bytes); const names = Object.keys(zip.files); if (names.includes("word/document.xml")) return { extensionFormat, contentFormat: "docx", evidence: ["ZIP container signature detected; word/document.xml identifies a DOCX package."], hardBinarySignature: true }; if (names.includes("content.xml") && names.includes("mimetype")) { const mime = (await zip.file("mimetype")?.async("text"))?.trim(); if (mime === "application/vnd.oasis.opendocument.spreadsheet") return { extensionFormat, contentFormat: "ods", evidence: ["ZIP container signature detected; ODS mimetype identifies an OpenDocument spreadsheet."], hardBinarySignature: true }; } if (names.includes("xl/workbook.xml") || names.some((name) => name.startsWith("xl/worksheets/"))) return { extensionFormat, contentFormat: "xlsx", evidence: ["ZIP container signature detected; xl/workbook.xml identifies an XLSX workbook."], hardBinarySignature: true }; evidence.push("ZIP container signature detected, but no supported office package signature was found."); } catch { evidence.push("ZIP container signature detected, but its package entries could not be inspected safely."); } }
  if (startsWith(u8, OLE_SIGNATURE)) { if (extensionFormat === "xls") return { extensionFormat, contentFormat: "xls", evidence: ["OLE/CFB signature detected; extension is .xls."], hardBinarySignature: true }; evidence.push("OLE/CFB signature detected; extension does not identify .xls."); }
  if (startsWith(u8, [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) { if (extensionFormat === "image-ocr") return { extensionFormat, contentFormat: "image-ocr", evidence: ["PNG image signature detected; OCR is required."], hardBinarySignature: true }; }
  if (startsWith(u8, [0xff, 0xd8, 0xff])) { if (extensionFormat === "image-ocr") return { extensionFormat, contentFormat: "image-ocr", evidence: ["JPEG image signature detected; OCR is required."], hardBinarySignature: true }; }
  if (extensionFormat === "image-ocr") return { extensionFormat, contentFormat: "unknown", evidence: ["The image extension was recognized, but a PNG/JPEG signature was not detected."], hardBinarySignature: true };
  const textBytes = u8.slice(0, Math.min(u8.length, 4 * 1024 * 1024)); const text = decodeUtf8(textBytes); const xmlHead = text.slice(0, 4096);
  if (extensionFormat === "xls" && /<Workbook\b[^>]*urn:schemas-microsoft-com:office:spreadsheet/i.test(xmlHead)) return { extensionFormat, contentFormat: "xls", evidence: ["Excel 2003 SpreadsheetML XML signature detected for the .xls extension."], hardBinarySignature: false };
  if (extensionFormat === "markdown-table" || looksLikeMarkdownTable(text)) return { extensionFormat, contentFormat: "markdown-table", evidence: ["Markdown pipe-table signature detected."], hardBinarySignature: false };
  if (looksLikeJson(text) || extensionFormat === "json-records") { const fullText = decodeUtf8(u8); if (looksLikeJson(fullText)) return { extensionFormat, contentFormat: "json-records", evidence: ["UTF-8 text parses as an array of JSON objects."], hardBinarySignature: false }; }
  if (extensionFormat === "csv" || extensionFormat === "tsv" || extensionFormat === "text-table") { const lines = text.split(/\r?\n/).filter((line) => line.trim() !== "").slice(0, 20); const candidates: Array<[string, SupportedFormat]> = [[",", "csv"], ["\t", "tsv"], [";", "csv"], ["|", "csv"]]; const scored = candidates.map(([delimiter, format]) => ({ delimiter, format, score: lines.reduce((sum, line) => sum + delimiterScore(line, delimiter), 0) })).sort((a, b) => b.score - a.score); const best = scored[0]; if (best && best.score > 0 && stableDelimitedTable(lines, best.delimiter)) { evidence.push(`Text signature suggests ${best.format.toUpperCase()}-style tabular data using delimiter ${JSON.stringify(best.delimiter)}.`); if (extensionFormat === "text-table") return { extensionFormat, contentFormat: "text-table", evidence, hardBinarySignature: false }; return { extensionFormat, contentFormat: best.format, evidence, hardBinarySignature: false }; } }
  if (extensionFormat !== "unknown") evidence.push(`Extension suggests ${extensionFormat}, but no matching tabular content signature was found.`);
  return { extensionFormat, contentFormat: "unknown", evidence: ["No supported tabular content signature detected.", ...evidence], hardBinarySignature: false };
}
