import type { ExtractionRequest, ExtractionResponse, WorkerFailure, WorkerSuccess } from "../models/Extraction.ts";
import type { CandidateTable, DataValue, ExtractionLogEntry, FileSource, SupportedFormat } from "../models/Dataset.ts";
import { detectFormat } from "./FormatDetector.ts";
import { parseDelimited } from "./parsers/CsvParser.ts";
import { parseSpreadsheet } from "./parsers/SpreadsheetParser.ts";
import { parseJsonRecords } from "./parsers/JsonParser.ts";
import { parseMarkdownTables } from "./parsers/MarkdownParser.ts";
import { parseDocx } from "./parsers/DocxParser.ts";
import { parsePdf, renderPdfPageToBlob } from "./parsers/PdfParser.ts";
import { ocrImage } from "./parsers/OcrParser.ts";
import { analyzeTableStructure } from "./TableStructure.ts";
import { makeId } from "../utils/ids.ts";

const ctx = self as unknown as { addEventListener: typeof self.addEventListener; postMessage: typeof self.postMessage };
function now(): string { return new Date().toISOString(); }
function makeSource(fileName: string, fileSize: number, mimeType: string | undefined, extensionFormat: SupportedFormat, detectedFormat: SupportedFormat, evidence: string[]): FileSource { const ext = fileName.toLowerCase().includes(".") ? `.${fileName.toLowerCase().split(".").pop()}` : ""; return { fileName, extension: ext, mimeType, sizeBytes: fileSize, detectedFormat, extensionFormat, detectionEvidence: evidence }; }
function confidenceFor(format: SupportedFormat): "High" | "Medium" | "Low" { if (["csv", "tsv", "xlsx", "xls", "ods", "json-records"].includes(format)) return "High"; if (["docx", "pdf-text", "markdown-table", "text-table"].includes(format)) return "Medium"; if (["pdf-ocr", "image-ocr"].includes(format)) return "Low"; throw new Error(`Unsupported format: ${format}`); }
function buildCandidate(source: FileSource, location: string, tool: string, rawRows: DataValue[][], headerRow: number, headers: string[], types: CandidateTable["inferredTypes"], flags: CandidateTable["sanityFlags"], settings: ExtractionRequest["settings"], metadata?: CandidateTable["extractionMetadata"], extraLog: ExtractionLogEntry[] = []): CandidateTable { const id = makeId("table"); const tableLog: ExtractionLogEntry[] = [...extraLog,{ timestamp: now(), stage: "ingestion", action: "TABLE_EXTRACTED", source: source.fileName, tool, tableId: id, location, reason: `Extracted ${Math.max(rawRows.length - 1, 0)} data rows x ${headers.length} columns.` }]; return { id, source, confidence: confidenceFor(source.detectedFormat), extractionTool: tool, location, rawRows, detectedHeaderRow: headerRow, columnNames: headers, inferredTypes: types, sanityFlags: flags, extractionLog: tableLog, settings, sourceCandidateTableIds: [id], extractionMetadata: metadata }; }
function withMismatchFlag(source: FileSource, candidates: CandidateTable[]): CandidateTable[] { if (source.extensionFormat === "unknown" || source.extensionFormat === source.detectedFormat) return candidates; return candidates.map((candidate) => ({ ...candidate, sanityFlags: [...candidate.sanityFlags,{ kind: "extension-signature-mismatch", message: `Extension suggests ${source.extensionFormat}, while content suggests ${source.detectedFormat}. Content detection was used for extraction.`, severity: "error" }] })); }
function noTableError(): Error { return new Error("No detectable table was found. Numbers appearing only in prose are not extracted. Use the manual table-entry/paste box to provide tabular data explicitly."); }
async function extractPdfWithOcr(request: ExtractionRequest, baseSource: FileSource, pageCount: number): Promise<CandidateTable[]> { const limit = Math.min(pageCount, request.settings.ocrPageLimit ?? 200); const candidates: CandidateTable[] = []; const source: FileSource = { ...baseSource, detectedFormat: "pdf-ocr", detectionEvidence: [...baseSource.detectionEvidence, `No selectable text table was reconstructed; OCR was used on ${limit} page${limit === 1 ? "" : "s"}.`] }; for (let page = 1; page <= limit; page += 1) { const imageBlob = await renderPdfPageToBlob(request.bytes, page); const ocr = await ocrImage(imageBlob, request.settings.ocrLanguage ?? "eng"); if (ocr.rows.length === 0) continue; const structure = analyzeTableStructure(ocr.rows); const flags = [...ocr.flags,{ kind: "ocr-low-confidence" as const, message: `OCR extraction confidence is low. Verify every value against the original PDF page ${page}.`, severity: "warning" as const }]; candidates.push(buildCandidate(source, `PDF page ${page} (OCR)`, "Tesseract.js", ocr.rows, structure.headerRow, structure.headers, structure.types, flags, request.settings, { pageCount, ocrMeanConfidence: ocr.meanConfidence })); } if (candidates.length === 0) throw noTableError(); return candidates; }
async function extract(request: ExtractionRequest): Promise<ExtractionResponse> { const detection = await detectFormat(request.fileName, request.bytes); if (detection.contentFormat === "unknown") { if (detection.hardBinarySignature || detection.extensionFormat === "unknown") throw new Error("Unsupported or malformed input. The extension and content signature do not identify a supported table format."); throw noTableError(); } let effectiveFormat = detection.contentFormat; let source = makeSource(request.fileName, request.fileSize, request.mimeType, detection.extensionFormat, effectiveFormat, detection.evidence); const baseLog: ExtractionLogEntry[] = [{ timestamp: now(), stage: "detection", action: "FILE_DETECTED", source: request.fileName, tool: "content-signature-detector", reason: `Extension: ${detection.extensionFormat}; content format: ${effectiveFormat}. ${detection.evidence.join(" ")}` }]; const candidates: CandidateTable[] = [];
  if (effectiveFormat === "csv" || effectiveFormat === "tsv") { const parsed = await parseDelimited(request.bytes, request.settings, effectiveFormat === "tsv" ? "\t" : undefined); candidates.push(buildCandidate(source, "file", "PapaParse", parsed.rawRows, parsed.headerRow, parsed.headers, parsed.types, parsed.flags, request.settings)); }
  else if (effectiveFormat === "json-records") { const parsed = parseJsonRecords(request.bytes, request.settings); candidates.push(buildCandidate(source, "JSON array records", "JSON.parse", parsed.rawRows, 0, parsed.headers, parsed.types, parsed.flags, request.settings)); }
  else if (effectiveFormat === "xlsx" || effectiveFormat === "xls" || effectiveFormat === "ods") { const parsed = parseSpreadsheet(request.bytes, request.settings); for (const sheet of parsed.sheets) candidates.push(buildCandidate(source, `sheet: ${sheet.name}`, "SheetJS", sheet.rawRows, 0, sheet.headers, sheet.types, sheet.flags, request.settings)); }
  else if (effectiveFormat === "docx") { const tables = await parseDocx(request.bytes); for (const table of tables) candidates.push(buildCandidate(source, table.name, "JSZip + OOXML", table.rawRows, 0, table.headers, table.types, table.flags, request.settings)); }
  else if (effectiveFormat === "markdown-table") { const text = new TextDecoder().decode(request.bytes); const tables = parseMarkdownTables(text); for (const table of tables) candidates.push(buildCandidate(source, table.name, "Markdown table parser", table.rawRows, 0, table.headers, table.types, table.flags, request.settings)); if (candidates.length === 0) throw noTableError(); }
  else if (effectiveFormat === "text-table") { const text = new TextDecoder().decode(request.bytes); const delimiterSettings = request.settings.delimiter === "auto" ? request.settings : { ...request.settings, delimiter: "\t" as const }; const parsed = await parseDelimited(new TextEncoder().encode(text).buffer, delimiterSettings); if (parsed.rawRows.length < 2 || parsed.headers.length < 2) throw noTableError(); candidates.push(buildCandidate(source, "plain-text table", "PapaParse", parsed.rawRows, parsed.headerRow, parsed.headers, parsed.types, parsed.flags, request.settings)); }
  else if (effectiveFormat === "pdf-text") { const parsed = await parsePdf(request.bytes, Math.min(200, request.settings.pdfMaxPages ?? 200), request.settings.pdfColumnTolerance ?? 10); if (parsed.tables.length > 0) { source = { ...source, detectedFormat: "pdf-text" }; parsed.tables.forEach((table) => candidates.push(buildCandidate(source, table.name, "pdf.js text positions", table.rawRows, 0, table.headers, table.types, table.flags, request.settings, { pageCount: parsed.pageCount, textItemCount: parsed.textChars }))); } else if (parsed.textChars < Math.max(20, parsed.pageCount * 8)) { effectiveFormat = "pdf-ocr"; candidates.push(...await extractPdfWithOcr(request, source, parsed.pageCount)); } else throw noTableError(); }
  else if (effectiveFormat === "image-ocr") { const blob = new Blob([request.bytes], { type: request.mimeType ?? "image/png" }); const result = await ocrImage(blob, request.settings.ocrLanguage ?? "eng"); if (result.rows.length === 0) throw noTableError(); source = { ...source, detectedFormat: "image-ocr" }; const structure = analyzeTableStructure(result.rows); const flags = [...result.flags,{ kind: "ocr-low-confidence" as const, message: "OCR extraction confidence is low. Verify every value against the original image.", severity: "warning" as const }]; candidates.push(buildCandidate(source, "image OCR", "Tesseract.js", result.rows, structure.headerRow, structure.headers, structure.types, flags, request.settings, { ocrMeanConfidence: result.meanConfidence })); }
  if (candidates.length === 0) throw noTableError(); const finalCandidates = withMismatchFlag(source, candidates); return { source, candidates: finalCandidates, extractionLog: [...baseLog, ...finalCandidates.flatMap((candidate) => candidate.extractionLog)] }; }
ctx.addEventListener("message", (event: MessageEvent<ExtractionRequest>) => { void extract(event.data).then((response) => { const message: WorkerSuccess<ExtractionResponse> = { ok: true, response }; ctx.postMessage(message); }).catch((error: unknown) => { const message: WorkerFailure = { ok: false, error: error instanceof Error ? error.message : String(error) }; ctx.postMessage(message); }); });
