import type { DataValue, ColumnTypeInference } from "../models/Dataset.ts";
import { inferTypes } from "./TypeInference.ts";
import { displayValue } from "../utils/values.ts";
import { runSanityChecks } from "./SanityChecks.ts";

export interface TableStructure { headerRow: number; headers: string[]; types: ColumnTypeInference[]; flags: ReturnType<typeof runSanityChecks>; }
export function detectHeaderRow(rows: DataValue[][]): number { if (rows.length === 0) return 0; const limit = Math.min(rows.length, 20); let bestIndex = 0; let bestScore = Number.NEGATIVE_INFINITY; for (let i = 0; i < limit; i += 1) { const row = rows[i] ?? []; const nonBlank = row.filter((cell) => cell !== null && displayValue(cell).trim() !== "").length; const unique = new Set(row.map((cell) => displayValue(cell).trim().toLowerCase()).filter(Boolean)).size; const textLike = row.filter((cell) => typeof cell === "string" && cell.trim() !== "").length; const numericLike = row.filter((cell) => typeof cell === "number" && Number.isFinite(cell)).length; const score = nonBlank * 2 + unique + textLike * 0.5 - numericLike * 0.5 - i * 0.25; if (score > bestScore) { bestScore = score; bestIndex = i; } } return bestIndex; }
function flagDuplicateOrBlankHeaders(headers: string[], flags: ReturnType<typeof runSanityChecks>): void { const seen = new Map<string, number[]>(); headers.forEach((header, index) => { const normalized = header.trim().toLowerCase(); if (!normalized) { flags.push({ kind: "ambiguous-value", columnIndex: index, message: `Header cell ${index + 1} is blank. The blank header was preserved and must be named during confirmation.`, severity: "error" }); return; } const locations = seen.get(normalized) ?? []; locations.push(index); seen.set(normalized, locations); }); seen.forEach((positions, header) => { if (positions.length < 2) return; flags.push({ kind: "ambiguous-value", columnIndex: positions[0], message: `Header ${JSON.stringify(header)} occurs more than once at extracted columns ${positions.map((i) => i + 1).join(", ")}. Rename duplicates before confirmation.`, severity: "error" }); }); }
export function analyzeTableStructure(rows: DataValue[][]): TableStructure { const headerRow = detectHeaderRow(rows); const columnCount = rows.reduce((max, row) => Math.max(max, row.length), 0); const headerValues = rows[headerRow] ?? []; const headers = Array.from({ length: columnCount }, (_, index) => displayValue(headerValues[index]).trim()); const dataRows = rows.slice(headerRow + 1); const types = inferTypes(dataRows, headers.length); const flags = runSanityChecks(dataRows, headers, types); flagDuplicateOrBlankHeaders(headers, flags); if (dataRows.length === 0 || columnCount === 0) flags.push({ kind: "empty-table", message: "No usable data rows or columns were detected.", severity: "error" }); return { headerRow, headers, types, flags }; }
