import type { ColumnTypeInference, DataValue } from "../models/Dataset.ts";
import { isBlank, parseNumberStrict, displayValue } from "../utils/values.ts";

const ISO_DATE = /^\d{4}-\d{2}-\d{2}(?:[T\s]\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:?\d{2})?)?$/;
const DECIMAL_POINT = /^[+-]?(?:\d+(?:\.\d+)?|\.\d+)(?:[eE][+-]?\d+)?$/;
const DECIMAL_COMMA = /^[+-]?\d{1,3}(?:\.\d{3})*,\d+$/;
function normalizedStrings(values: DataValue[]): string[] { return values.filter((value) => !isBlank(value)).map((value) => displayValue(value).trim()); }
export function inferColumn(values: DataValue[]): ColumnTypeInference { const nonBlank = normalizedStrings(values); if (nonBlank.length === 0) return { type: "string", confidence: "low", ambiguous: true }; const allBoolean = nonBlank.every((value) => /^(true|false)$/i.test(value)); if (allBoolean) return { type: "boolean", confidence: "high", ambiguous: false }; const hasCommaFormat = nonBlank.some((value) => DECIMAL_COMMA.test(value)); const hasDotFormat = nonBlank.some((value) => DECIMAL_POINT.test(value)); if (hasCommaFormat && hasDotFormat) return { type: "string", confidence: "high", ambiguous: true }; const numberConvertible = values.filter((value) => !isBlank(value)).every((value) => parseNumberStrict(value) !== null || typeof value === "number"); if (numberConvertible) return { type: "number", confidence: "high", ambiguous: false }; if (nonBlank.every((value) => ISO_DATE.test(value))) return { type: "date", confidence: "medium", ambiguous: false }; const looksNumeric = nonBlank.some((value) => DECIMAL_POINT.test(value) || DECIMAL_COMMA.test(value)); if (looksNumeric) return { type: "string", confidence: "high", ambiguous: true }; return { type: "string", confidence: "high", ambiguous: false }; }
export function inferTypes(rows: DataValue[][], columnCount: number): ColumnTypeInference[] { return Array.from({ length: columnCount }, (_, columnIndex) => inferColumn(rows.map((row) => row[columnIndex] ?? null))); }
